### ISSUE TITLE
update the code

### ISSUE THREAD

**Issue by hechengbo-H** [zilin-huang/HAIM-DRL#1]
Hi, I'm very intrigued by your work. According to your profile, I understand that you were planning to update the code before February 23rd. However, it seems that the latest updates haven't been made yet. I was wondering if it would be possible for you to update the code at your earliest convenience. It would be greatly appreciated.

**Comment by zilin-huang** [comment]
Hi, thank you for reaching out and for your interest in our work! The code has been updated and uploaded as promised. Please feel free to check it out at your convenience. If you encounter any issues or have any questions regarding the code or its implementation, don't hesitate to ask. I'm here to help!
