### ISSUE TITLE
Error in execution of the quick start training

### ISSUE THREAD

**Issue by apighetti** [zilin-huang/HAIM-DRL#2]
Hi! 
I am very interested in your work and wanted to try out the method for myself for further research purposes. I just followed the installation guide, but upon trying to run the quick start experiment, the metadrive window would just open and close immediately and not rendering the scene.

Here is the error I'm getting:
AttributeError: module 'gltf' has no attribute 'patch_loader'

Which can be also seen in detail in the attached experiment json output.
[experiment_state-2024-03-19_11-47-15.json](https://github.com/zilin-huang/HAIM-DRL/files/14650140/experiment_state-2024-03-19_11-47-15.json)

Thank you in advance for your help!

**Comment by zilin-huang** [comment]
Hi, for this issue, you can fix it with the following command "pip install panda3d-gltf==0.13".

**Comment by apighetti** [comment]
Thank you, that fixed it!
