### ISSUE TITLE
error when train

### ISSUE THREAD

**Issue by tongyuyu** [zilin-huang/HAIM-DRL#3]
I have configured according to the readme, but there is an error when I run it. May I know why?
![image](https://github.com/user-attachments/assets/768a5b02-f9cb-40ee-8f13-97beca91923c)
![image](https://github.com/user-attachments/assets/3f6fc635-0f3d-4e43-9d17-144ea62ec0df)
![image](https://github.com/user-attachments/assets/ffc8ac81-cf87-442e-af1e-578082ee57ca)
![image](https://github.com/user-attachments/assets/3b9d2cea-88d9-4f18-9976-37497f5f8ed3)

**Comment by zilin-huang** [comment]
Hi,

I haven't encountered this issue before. I tested the code from scratch today on a computer equipped with NVIDIA 4090/4080/3070 and 3060 GPUs, and it ran successfully. Could you please let me know which GPU version you are using? I'm not sure if this could be related.

Thank you.
